dbt-labs/semantic-layer-sdk-python

.github/actions/setup-python-env/action.yaml, .github/workflows/publish.yaml
This commit adds a CI action that can publish to PyPI. There will be two release environments: `release`, which publishes to the actual PyPI, and `relase-test`, which publishes to the test PyPI repo. We can use the second one for testing this workflow.
=> ci(pypi-publish): add CI for publishing to PyPI

.github/workflows/publish-test.yaml
Apparently we need to create a different workflow if we want to run in a separate environment.
=> ci(pypi-publish): create test CI action

CONTRIBUTING.md, pyproject.toml
This commit adds two new environments to hatch which install the SDK from the test PyPI repo at `https://test.pypi.org/simple/`. This is to make sure our build and publish pipelines work whenever we make a change to them.
=> chore: add `pypi-test-*` envs

dbtsl/__init__.py, dbtsl/api/adbc/client/asyncio.py, dbtsl/api/adbc/client/base.py, dbtsl/api/adbc/client/sync.py, dbtsl/api/graphql/client/base.py
This commit moves some constants over from `env` to their own classes, and makes the clients have a `PROTOCOL` instance in them. This will make it easier to extend further later.
=> refactor(defaults): better defaults

.changes/unreleased/Fixes-20240618-124639.yaml, .github/workflows/changelog-check.yaml, dbtsl/api/graphql/client/sync.py, dbtsl/client/sync.py, pyproject.toml, tests/test_imports.py
The previous version of the package was raising errors on Python 3.9 due to importing `Self` from `typing`, which was introduced in 3.10. I changed it to `typing_extensions`, and added a test for importing all modules to avoid errors like this in the future.
=> fix: import error on 3.9

.changes/unreleased/Chore-20240618-132741.yaml, pyproject.toml
That config was using the old name.
=> chore(ruff): known-first-party config was wrong

.changes/unreleased/Under the Hood-20240618-163932.yaml, .lefthook/commit-msg/template-checker, README.md, dbtsl/api/adbc/client/base.py, dbtsl/api/graphql/client/base.py, dbtsl/env.py
This commit adds a `User-Agent` header for telemetry so that we know which requests are coming from the SDK.
=> internal: add `user-agent` header for telemetry

.changes/unreleased/Fixes-20240618-180037.yaml, dbtsl/backoff.py
`ExponentialBackoff` was had `exp_factor` hardcoded to 1.15.
=> fix: backoff was not using `exp_factor`

.changes/unreleased/Under the Hood-20240620-130850.yaml, dbtsl/api/graphql/client/asyncio.py, dbtsl/api/graphql/client/base.py, dbtsl/api/graphql/client/sync.py, dbtsl/api/graphql/protocol.py, tests/api/graphql/test_client.py
This commit refactors some of the internals of the GraphQL clients so that the `_poll_until_complete` method now accepts any kind of query job. This will make it more extensible for other kinds of queries such as exports.
=> refactor: change how clients poll and create queries

.changes/unreleased/Test-20240621-171539.yaml, .github/workflows/code-quality.yaml, CONTRIBUTING.md, pyproject.toml
Since integration tests are more expensive, we separated them to run only after unit tests have succeeded. We also don't need to repeat them for every python version, so in CI they will only run in Python 3.12.
=> test: separate unit and integration tests

.changes/unreleased/Under the Hood-20240628-164812.yaml, dbtsl/models/__init__.py, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/measure.py, dbtsl/models/metric.py, dbtsl/models/query.py, tests/test_models.py
This commit adds automatic mashumaro camel case aliases for all fields in our models. This will make them more scalable and less error-prone.
=> refactor: add automatic `camelCase` mashumaro aliases for `snake_case` attributes

.changes/unreleased/Features-20240709-103228.yaml, .changes/unreleased/Features-20240709-103239.yaml, .changes/unreleased/Features-20240709-103250.yaml, .changes/unreleased/Features-20240709-103258.yaml, .changes/unreleased/Under the Hood-20240709-103311.yaml, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/api/graphql/util.py, dbtsl/client/asyncio.pyi, dbtsl/client/sync.pyi, dbtsl/models/__init__.py, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/entity.py, dbtsl/models/measure.py, dbtsl/models/metric.py, dbtsl/models/query.py, dbtsl/models/saved_query.py, dbtsl/models/time_granularity.py, examples/list_metrics_sync.py, examples/list_saved_queries_async.py, tests/api/graphql/test_util.py, tests/integration/test_gql.py, tests/test_models.py
This commit improves the models that can be fetched via the GraphQL API.
Added models:
- Saved Query
- Entity
Improved models:
- Dimension
- Metric
It also improves our GraphQL generation logic so that models will automatically generate their queries based on the dataclass fields.
=> Improve GraphQL API models

.changes/unreleased/Test-20240709-114648.yaml, tests/api/graphql/test_client.py, tests/conftest.py, tests/integration/test_gql.py
This commit merges our sync and async tests so that now they use the `maybe_await` function to reuse logic.
=> test: merge sync/async tests and fix warnings

.changes/unreleased/Chore-20240709-115016.yaml, lefthook.yaml
Lefthook was leaving files behind whenever there was any formatting or linting changes. This should fix it.
=> chore: add `stage_fixed` to lefthook

.changes/unreleased/Features-20240709-121955.yaml, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, tests/api/adbc/test_protocol.py
This commit adds all supported params to our `query` methods in both GraphQL and ADBC.
Before, we were just using the `metrics` filter.
=> feat: full query parameters

.changes/unreleased/Dependencies-20240819-132546.yaml, pyproject.toml
This commit lowers the minimum supported pyarrow version. We can do that with no code changes and the SDK still works and all [unit and integration tests pass](https://github.com/dbt-labs/semantic-layer-sdk-python/actions/runs/10452463632/job/28940925527?pr=40).
=> deps: lower minimum `pyarrow` version

.changes/unreleased/Features-20240819-130313.yaml, .changes/unreleased/Features-20240819-130327.yaml, dbtsl/models/__init__.py, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/metric.py, dbtsl/models/saved_query.py, dbtsl/models/time.py
Thid commit adds `Exports` and `QueryParams` to the fields of a saved query. This makes querying for them more useful than just returning a name, description and label.
To make this work, I had to add an extra check in the base `GraphQLFragmentMixin` class (the thing that generates GQL from the dataclasses) because it didn't handle `Optional` field well.
=> feat: add extra fields to `SavedQuery`

.changes/unreleased/Under the Hood-20240906-184939.yaml, dbtsl/backoff.py, dbtsl/error.py, tests/test_error.py
This commit makes our error messages better since our errors weren't stringifying properly. It also adds a `timeout_ms` parameter to the `TimeoutError` so users get a proper feedback of what the current timeout is set at.
=> refactor: make error strings better

.changes/unreleased/Fixes-20240920-202558.yaml, dbtsl/client/sync.pyi, tests/integration/test_sl_client.py
The sync client had an `async` method in its type annotations, which probably got there by my fast copy pasting. This commit fixes that.
=> fix: wrong type annotation in for `saved_queries`

.changes/unreleased/Features-20240920-201139.yaml, .changes/unreleased/Under the Hood-20240920-201151.yaml, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, dbtsl/client/asyncio.pyi, dbtsl/client/sync.pyi, tests/api/graphql/test_client.py, tests/api/graphql/test_protocol.py, tests/integration/test_sl_client.py, tests/test_models.py
This PR adds saved queries to `query` and `compile_sql`. I used `@overload` so that users have the option to statically typecheck for correct usage of the args, i.e that they're not using `metrics` and `group_by` with `saved_query`. I also added a client-side validation for query parameters before we submit queries to the servers.
=> feat: saved queries in `query` and `compile_sql`

.changes/unreleased/Under the Hood-20241008-160709.yaml, dbtsl/api/adbc/client/base.py, dbtsl/error.py, tests/test_error.py
This commit adds explicit logging of `self.args` in `SemanticLayerError` so that users get a proper display of the underlying error when they `str(e)` or `repr(e)`.
It also adds `raise from` in `_handle_error` to add more context to the exceptions raised via ADBC.
=> refactor: fix error messages

.changes/unreleased/Breaking Changes-20241001-160946.yaml, .changes/unreleased/Features-20241001-155522.yaml, .changes/unreleased/Fixes-20241001-155448.yaml, .changes/unreleased/Under the Hood-20241001-155544.yaml, dbtsl/__init__.py, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, dbtsl/client/asyncio.pyi, dbtsl/client/sync.pyi, tests/api/adbc/test_protocol.py, tests/integration/test_sl_client.py, tests/test_models.py
This PR changes the internal representation of `QueryParameters` to add stricter validation and fix the ambiguity of `order_by` parameters when sent via GraphQL. It also exposes new `OrderByMetric` and `OrderByGroupBy` top-level objects so that users can specify their clauses more precisely if strings don't suffice.
I recommend you review this commit by commit :)
To facilitate typing across different classes, we created a `QueryParameters` class that is a `TypedDict`. While this is convenient for static typing of `kwargs`, `TypedDicts` don't do any validation. To fix that, I created two dataclasses: `AdhocQueryParametersStrict` and `SavedQueryQueryParametersStrict`, which represent "strictly" validated parameters that are ready to be sent to the API. Then, I improved the …
=> fix: `order_by` for `compile_sql` now works as expected

.changes/unreleased/Deprecations-20241017-163158.yaml, .changes/unreleased/Features-20241017-163057.yaml, .changes/unreleased/Under the Hood-20241017-163037.yaml, .changie.yaml, dbtsl/__init__.py, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/client/base.py, dbtsl/api/shared/query_params.py, dbtsl/asyncio.py, dbtsl/models/__init__.py, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/metric.py, dbtsl/models/saved_query.py, dbtsl/models/time.py, tests/api/adbc/test_protocol.py, tests/test_models.py
This PR adds support for custom grain and deprecates old fields that use the `TimeGranularity` enum. I also deprecated `TimeGranularity` itself.
I recommend reviewing commit by commit :)
=> feat: support for custom grain

.changes/unreleased/Fixes-20241111-182559.yaml, dbtsl/api/graphql/protocol.py, tests/api/graphql/test_protocol.py, tests/conftest.py, tests/integration/test_sl_client.py, tests/query_test_cases.py, tests/test_models.py
This commit fixes some serialization issues that were showing up with `orderBy` and `where` for the GraphQL protocol. This was affecting `compile_sql()` mainly since queries go via ADBC.
To avoid regressions, I added checks for variable values in the GraphQL tests. It will try to serialize those variable values and bind them to the query using `graphql` utilities. If the query is not valid, i.e the query + variables do not respect the server schema, it will fail. This requires no connection to the server other than fetching the schema.
I also added integration tests that will connect to the server. This will only run after unit test, though, so these issues should be caught before integration tests.
=> fix: serialization issues in GraphQL `orderBy` and `where`

.changes/unreleased/Features-20241112-154335.yaml, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, dbtsl/client/asyncio.pyi, dbtsl/client/sync.pyi, tests/query_test_cases.py, tests/test_models.py
This PR adds support for adhoc queries with only `group_by`, without a `metric`. This is equivalent to doing `client.dimension_values("my_dimension")`, but since the raw APIs support it, I thought it would be nice to keep parity here as well.
I changed the validation logic to allow this, and I added unit and integration test cases to cover it. I also changed the `.pyi` files so that users get LSP suggestions for this use case.
You can review by commit.
=> feat: add support for groupby-only adhoc queries

.changes/unreleased/Chore-20241114-150932.yaml, .github/workflows/create-release-pr.yaml
It was using the wrong version name, which resulted in PRs with the wrong name.
=> ci: fix CI that creates release titles

.changes/unreleased/Features-20241213-104739.yaml, dbtsl/api/adbc/client/base.py
A batch can contain up to 1024 rows. If the columns contain large
amounts of data (json blogs or free text), the total batch size can
exceed the max message size. By doubling this we should be able to
accommodate most use cases.
TODO: if we hear of people reaching this max, maybe we should make it
configurable.
=> feat: increase maximum message size

.changes/unreleased/Deprecations-20250212-124416.yaml, .changes/unreleased/Features-20250211-174833.yaml, .changes/unreleased/Features-20250212-131405.yaml, dbtsl/api/graphql/client/asyncio.py, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/base.py, dbtsl/api/graphql/client/sync.py, dbtsl/api/graphql/client/sync.pyi, dbtsl/backoff.py, dbtsl/client/asyncio.py, dbtsl/client/asyncio.pyi, dbtsl/client/base.py, dbtsl/client/sync.py, dbtsl/client/sync.pyi, dbtsl/error.py, dbtsl/timeout.py, tests/conftest.py, tests/integration/conftest.py, tests/integration/test_sl_client.py, tests/integration/test_timeouts.py, tests/test_error.py, tests/test_timeout.py, tests/util.py
This PR adds a new `timeout` parameter to the global `SemanticLayerClient` that gets passed down to the `GraphQLClient`.
The `timeout` parameter is a `TimeoutOptions` enum, which contains:
- `connection_timeout`: timeout to establish a connection to the servers
- `execute_timeout`: timeout to run an operation against the server (not counting retries)
- `tls_close_timeout`: timeout to close a TLS connection
- `total_timeout`: timeout for total wall time of an operation like `query()` or `dimensions()`, including retries, from the caller's point of view
Users can also pass in `int` or `float` values, which should be interpreted as equivalent to setting `total_timeout`. In practice, this gets converted to `TimeoutOptions` by assigning that same value to everything. Since everything should be …
=> feat: revamp timeouts

.changes/unreleased/Chore-20250327-101226.yaml, .github/workflows/publish.yaml
I found out that the `tags` field in the Github Workflow specification is not a regex, but their own pattern matcher syntax. This caused our release to fail, so I'm fixing it so we can release.
=> chore: Fix release CI regex

.changes/unreleased/Fixes-20250327-184148.yaml, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/entity.py, dbtsl/models/measure.py, dbtsl/models/metric.py, dbtsl/models/query.py, dbtsl/models/saved_query.py, dbtsl/models/time.py, tests/test_models.py
This commit adds a new `FlexibleEnumMeta` enum metaclass that can be added to enums to make them accept arbitrary values as input and return a special `UNKNOWN` entry.
I added some tests that will assert all enums exported by the SDK will use this metaclass, and that all of them declare the `UNKNOWN` attribute with the correct value.
=> fix: Create `FlexibleEnumMeta` enum metaclass

.changes/unreleased/Chore-20250331-133422.yaml, .github/workflows/code-quality.yaml, .github/workflows/publish.yaml
This commit adds the code quality (lint, format, unit/integration tests) checks after merge to `main` and before publishing to PyPI. This is just an extra sanity check to be extra sure we won't publish bad code accidentally.
=> ci: add code checks on merge to `main` and publish

.changes/unreleased/Chore-20250403-163034.yaml, .github/workflows/code-quality.yaml, dbtsl/__init__.py, dbtsl/api/adbc/client/asyncio.py, dbtsl/api/adbc/client/base.py, dbtsl/api/adbc/client/sync.py, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/client/asyncio.py, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/base.py, dbtsl/api/graphql/client/sync.py, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, dbtsl/asyncio.py, dbtsl/client/asyncio.pyi, dbtsl/client/base.py, dbtsl/client/sync.pyi, dbtsl/error.py, dbtsl/models/__init__.py, dbtsl/models/base.py, lefthook.yaml, pyproject.toml, tests/api/graphql/test_client.py, tests/api/graphql/test_protocol.py, tests/integration/test_sl_client.py, tests/integration/test_timeouts.py
This PR upgrade pyright `typeCheckingMode` from `standard` to `strict`, and it also adds `mypy` typechecking to the pre-commit hooks and to CI.
This is an attempt to make sure our type definitions are very sound, and will hopefully catch some bugs in the future.
There were some exceptions where I had to resort to `# type: ignore`. 
Most of them are due to incomplete type annotations on third party libraries, which triggers the `reportUnknownArgumentType` or `reportUnknownVariable` checks from pyright (cough cough `pyarrow`).
Some other exceptions are due to there being to way to type things like `Unpack[T]` where `T` is not a concrete `TypedDict` and is instead a `TypeVar` that is bound to a `TypedDict`. In such cases, I added comments explaining why the ignore is necessary. Yes, I could …
=> chore: make `pyright` run in `strict` mode and add `mypy`

.changes/unreleased/Features-20250327-224851.yaml, dbtsl/api/adbc/protocol.py, dbtsl/api/graphql/protocol.py, dbtsl/api/shared/query_params.py, tests/api/adbc/test_protocol.py, tests/query_test_cases.py, tests/test_models.py
This PR adds the grain option to the group by field. This makes it easier to define a grain without using dunder syntax.
=> Add support to pass in typed group by

.changes/unreleased/Fixes-20250409-201106.yaml, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/shared/query_params.py, dbtsl/client/asyncio.pyi, dbtsl/client/sync.pyi
In [my last PR](https://github.com/dbt-labs/semantic-layer-sdk-python/pull/70), I neglected to update the type information for the query method in some instances. This fixes that by allowing `Union[GroupByParam, str]` instead of just `str` for group_by params.
=> Fix type of group_by in query method

.changes/unreleased/Features-20250414-170939.yaml, README.md, dbtsl/api/graphql/client/asyncio.py, dbtsl/api/graphql/client/asyncio.pyi, dbtsl/api/graphql/client/base.py, dbtsl/api/graphql/client/sync.py, dbtsl/api/graphql/client/sync.pyi, dbtsl/api/graphql/protocol.py, dbtsl/client/asyncio.py, dbtsl/client/asyncio.pyi, dbtsl/client/base.py, dbtsl/client/sync.py, dbtsl/client/sync.pyi, dbtsl/models/__init__.py, dbtsl/models/base.py, dbtsl/models/dimension.py, dbtsl/models/entity.py, dbtsl/models/measure.py, dbtsl/models/metric.py, dbtsl/models/query.py, dbtsl/models/saved_query.py, examples/list_metrics_lazy_sync.py, pyproject.toml, tests/api/graphql/test_client.py, tests/api/graphql/test_protocol.py, tests/api/graphql/test_util.py, tests/integration/test_sl_client.py, tests/test_models.py
This PR introduces new functionality to allow models to lazy load certain large fields if users want to. This is only used in `Metric.dimensions`, `Metric.entities` and `Metric.measures` for now, but can easily be expanded to other fields in the future if we deem necessary.
There are no breaking changes.
This is what it looks like from an end user perspective:
```python
from dbtsl import SemanticLayerClient
def main():
sl = SemanticLayerClient(..., lazy=True)
with sl.session():
metrics = sl.metrics()
metric = metrics[0]
assert metric.dimensions == []
loaded = metric.load_dimensions()
assert len(loaded) > 0
assert loaded == metric.dimensions
main()
```
The `asyncio` equivalent is:
```python
import asyncio
from dbtsl.asyncio import AsyncSemanticLayerClient
async def main():
sl = …
```
=> feat: add lazy loading

.changes/unreleased/Fixes-20250414-204039.yaml, dbtsl/api/adbc/protocol.py, dbtsl/api/shared/query_params.py, tests/api/adbc/test_protocol.py
In my original implementation, I assumed that `Dimension` was an alias for `TimeDimension`. I know we talked about doing that at some point, but I guess we never implemented that. So, this PR makes a distinction between `Dimension` and `TimeDimension` parameters.
=> Fix TimeDimension in group_by

.changes/unreleased/Features-20250416-142848.yaml, constraints/README.md, constraints/py313.txt, pyproject.toml
This commit adds support for Python 3.13 in the package metadata. There were no code changes required.
As usual, we had to add some constraints to our dependencies directly. Namely:
- `pyarrow` only supports Python 3.13 from v18.0.0 onwards
- `typing-extensions ` only supports Python 3.13 from v4.12.0 onwards
Direct dependencies are hard enforced by pip when installing the package, and users won't be able to install if their project requires an older version.
Additionally, I had to add constraints to two transitive dependencies:
- `frozenlist` only supports Python 3.13 from v1.5.0 onwards
- `importlib-resources` only supports Python 3.13 from v6.0.0 onwards
Transitive dependencies are NOT envorced by pip when installing the package, and users need to manually add constraints to them. This …
=> feat: officially support Python 3.13

.changes/unreleased/Fixes-20250721-115455.yaml, .gitignore, CONTRIBUTING.md, dbtsl/api/adbc/protocol.py, tests/api/adbc/test_protocol.py
These should not be necessary, and using subqueries without aliases in Postgres causes an error.
=> Remove unnecessary subqueries
